import type { Metadata } from "next";
import {Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import "bootstrap-icons/font/bootstrap-icons.css";

const plusJakartaSans = Plus_Jakarta_Sans({subsets:["latin"], weight:["400","700"] } );


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={plusJakartaSans.className}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
